#! /bin/bash

find . -depth |
while read LONG; do
   SHORT=$( basename "$LONG" | sed -e 's/[^A-Za-z0-9._-]/_/g')
   DIR=$( dirname "$LONG" )
   if [ "${LONG}" != "${DIR}/${SHORT}"  ]; then
     mv "${LONG}" "${DIR}/${SHORT}"
   fi
done
